// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    'catalog/index',
    {
      type: 'category',
      label: 'Requirements',
      items: [{ type: 'autogenerated', dirName: 'catalog/requirements' }],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'catalog/architecture' }],
    },
    {
      type: 'category',
      label: 'Development',
      items: [{ type: 'autogenerated', dirName: 'catalog/development' }],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{ type: 'autogenerated', dirName: 'catalog/operations' }],
    },
    {
      type: 'category',
      label: 'Guide',
      items: [{ type: 'autogenerated', dirName: 'guide' }],
    },
  ],
};

module.exports = sidebars;
