// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home'
    },
    {
      type: 'category',
      label: 'Requirements',
      link: { type: 'doc', id: 'requirements/index' },
      items: [{ type: 'autogenerated', dirName: 'requirements' }],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'doc', id: 'architecture/index' },
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Development',
      link: { type: 'doc', id: 'development/index' },
      items: [{ type: 'autogenerated', dirName: 'development' }],
    },
    {
      type: 'category',
      label: 'Operations',
      link: { type: 'doc', id: 'operations/index' },
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
    {
      type: 'html',
      value: '<div class="nav-divider"></div>',
    },
    {
      type: 'category',
      label: 'Personas',
      link: { type: 'doc', id: 'personas/index' },
      items: [{ type: 'autogenerated', dirName: 'personas' }],
    },
  ],
};

module.exports = sidebars;
